
version: '3.4'

services:
  paymentconsumer:
    image: paymentconsumer
    build:
      context: .
      dockerfile: payment-consumer/Dockerfile
    depends_on:
      - rabbitmq
  paymentexecutorinternal:
    image: paymentexecutorinternal
    build:
      context: .
      dockerfile: payment-executor-internal/Dockerfile
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.11-rc-management
    container_name: payment-consumer-rabbit
    ports:
      - 15672:15672
      - 5672:5672
